Suggestions from Jos
EasyScience/EasyReflectometryLib pull request #106
Opened 2024-03-05 07:46 UTC by andped10

Revert `solvent_surface_coverage` to `solvation`
- Solvation is the term used in the reflectometry community

Change data files (.ort)
- Metadata changed from `neutrons` to `neutron`
- Okay to make changes to the meta data to prevent warnings in examples / tests
- No changes to numerical data

Change final line in solvation.ipynb
- To clarify what is being done

2024-03-05 09:35 UTC, jfkcooper requested changes
Mostly fine, but the surfactant should be described by a single solvation parameter, rather than one for the head and another for the tail, since this doesn't make so much physical sense (to allow them to be different while forcing the number of head and tail groups to be the same).

2024-03-05 09:35 UTC, jfkcooper commented on EasyReflectometry/sample/assemblies/surfactant_layer.py
> -        tail_layer_solvent_surface_coverage: float,
Though they can be solvated by different things, so `head_layer_solvent` and `tail_layer_solvent` are fine

2024-03-05 09:35 UTC, jfkcooper commented on EasyReflectometry/sample/elements/layers/layer_apm.py
> +        :param solvation: Fraction of layer not covered by molecule.
"Fraction of layer not covered by molecule." --> "Fraction of layer not covered by surfactant layer"

2024-03-05 09:35 UTC, jfkcooper commented on EasyReflectometry/sample/elements/layers/layer_apm.py
>          """Get the fraction of layer not covered by molecules."""
molecules --> surfactant

2024-03-05 09:35 UTC, jfkcooper commented on EasyReflectometry/sample/elements/layers/layer_apm.py
>          """Set the fraction of layer not covered by molecules.
molecules --> surfactant

2024-03-05 09:35 UTC, jfkcooper commented on docs/sample/assemblies_library.rst
> +    head_solvation = 0.2
This is not a good example, as there must be the same number of head and tail groups, so the solvation should be the same

2024-03-05 09:35 UTC, jfkcooper commented on docs/tutorials/multi_contrast.ipynb
> +    "tail_solvation = 0.0\n",
THis is not a good example as the head and tail groups have to be equal, so the solvation should be the same between them

2024-03-05 09:53 UTC, arm61 commented on EasyReflectometry/sample/assemblies/surfactant_layer.py
> -        tail_layer_solvent_surface_coverage: float,
I think they can be solvated differently, i.e., a hydrophilic head will have more water (more solvation) than a hydrophobic tail no?

2024-03-05 09:55 UTC, jfkcooper commented on EasyReflectometry/sample/assemblies/surfactant_layer.py
> -        tail_layer_solvent_surface_coverage: float,
The head will have more water yes, but if we are talking about solvation in terms of surface coverage, then no (at least from my point of view). The head group SLD needs to be defined in terms of some fraction of water, and then the whole structure has some surface coverage, which I think is being called the salvation in this case.

2024-03-05 11:29 UTC, jfkcooper commented on EasyReflectometry/sample/assemblies/surfactant_layer.py
> -        tail_layer_solvent_surface_coverage: float,
After some discussion, we came to the conclusion that we are talking about slightly different things, and yes they can be solvated differently, but the coverage for both must be the same, so something like `head_solvation` and `tail_solvation` should exist, but so should `coverage`.

2024-03-12 06:56 UTC, andped10 commented
Was handled in #109

2024-03-12 06:56 UTC, closed without merging