Removal of poetry
easyScience/EasyReflectometryLib pull request #58
Opened 2023-01-23 13:02 UTC by arm61

This is part of a bigger rebuild of the CI for the whole of EasyReflectometry.

2023-01-24 16:00 UTC, wardsimon requested changes

2023-01-24 16:00 UTC, wardsimon commented on docs/installation.rst
> +    $ pip install git+https://github.com/easyScience/EasyReflectometryLib.git@master[dev]
Why the dev version?
`pip install git+https://github.com/easyScience/EasyReflectometryLib.git` whould be better

2023-01-24 16:00 UTC, wardsimon commented on pyproject.toml
> +    "easyScienceCore @ git+https://github.com/easyScience/easyCore.git@mutlifitter",
Are we still `multifitter`?

2023-01-24 16:15 UTC, arm61 commented
@wardsimon I agree

2023-01-25 09:40 UTC, wardsimon approved these changes

2023-01-25 09:41 UTC, merged